# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'TQIBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TQIBank
  pod 'VFNetwork'
  
  pod 'TQICoordinator', :git => 'https://github.com/vafreitas/ios-mod-coordinator.git'
  pod 'TQIExtract', :git => 'https://github.com/vafreitas/ios-mod-extract.git'

  target 'TQIBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TQIBankUITests' do
    # Pods for testing
  end

end
