# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TQIBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TQIBank
  pod 'VFNetwork'

  target 'TQIBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TQIBankUITests' do
    # Pods for testing
  end

end
